// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://caijygaslduihfxzgtrw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNhaWp5Z2FzbGR1aWhmeHpndHJ3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzQ5OTU4NjEsImV4cCI6MjA1MDU3MTg2MX0.VsJsKPyisp_Ytj2MHlvGsmomBhArrUp0PDtOkkNfgCY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);